/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p3;

import java.awt.Color;
import java.awt.Frame;

/**
 *
 * @author alvar
 */
public class PilaFrame extends java.awt.Frame {

    /**
     * Creates new form PilaFrame
     */
    public PilaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        
        final int ancho = 800, alto = 600;
        PilaFrame pf = new PilaFrame();
        CanvasPila cp = new CanvasPila(10);
        
        cp.setSize(ancho, alto);
        
        
        pf.setSize(ancho, alto);
        pf.add(cp);
        pf.setVisible(true);
        
        
        
        PilaLenta p = new PilaLenta(10, cp);
        
        Thread productor1 = new Productor(p);
        Thread productor2 = new Productor(p);
        Consumidor consumidor = new Consumidor(p);
        Thread consumidor1 = new Thread(consumidor), consumidor2 = new Thread(consumidor);
        
        productor1.start();
        productor2.start();
        productor1.join();
        productor2.join();
        System.out.println("\n");
        consumidor1.start();
        consumidor2.start();
        consumidor1.join();
        consumidor2.join();
        System.out.println("\nPila: " + p);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
