/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.CanvasTienda;
import Clases.Comprar;
import Clases.Reparar;
import Clases.Tienda;
import java.awt.Color;
import java.util.Random;

/**
 *
 * @author anton
 */
public class Frame extends java.awt.Frame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        
        Frame f = new Frame();
        CanvasTienda ct = new CanvasTienda();
        
         f.setBackground(Color.cyan);
        f.setTitle("Practica 5 - PCD");  
        f.setSize(500,600);
        f.add(ct);
        f.setResizable(false);     
        f.setVisible(true);
        
        Thread[] clientes = new Thread[10];
        
        
        Tienda tienda = new Tienda(ct);
        
        Random r = new Random();
        r.setSeed(System.nanoTime());
        
        for(int i = 0 ; i < 10 ; i++)
        {
            if(r.nextInt(10) <= 4)
            {
                clientes[i] = new Comprar(tienda);
                clientes[i].start();
               
            }else
            {
                clientes[i] = new Thread (new Reparar(tienda));
                clientes[i].start();
               
            }
             Thread.sleep(r.nextInt(1+1)*1000);
        }
        
        for(int i = 0 ; i < 10 ;i++)
        {
            clientes[i].join();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
