/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author anton
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private static final String DIRECCION = "C:\\Users\\anton\\Desktop\\CURSO\\PracticasActuales\\AMC\\datosPr2\\";
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        CadenaManualFichero = new javax.swing.JTextField();
        AFDFichero = new javax.swing.JButton();
        AFNDFichero = new javax.swing.JButton();
        AFNDTexto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ZonaEscritura = new javax.swing.JTextArea();
        jFileChooser1 = new javax.swing.JFileChooser();
        AFDTexto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CadenaManualTexto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Cadena");

        AFDFichero.setText("Ejecutar AFD");
        AFDFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFDFicheroActionPerformed(evt);
            }
        });

        AFNDFichero.setText("Ejecutar AFND");
        AFNDFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFNDFicheroActionPerformed(evt);
            }
        });

        AFNDTexto.setText("Ejecutar AFND");
        AFNDTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFNDTextoActionPerformed(evt);
            }
        });

        ZonaEscritura.setColumns(20);
        ZonaEscritura.setRows(5);
        jScrollPane1.setViewportView(ZonaEscritura);

        AFDTexto.setText("Ejecutar AFD");
        AFDTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFDTextoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setText("AUTOMATAS DESDE FICHERO");

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setText("AUTOMATAS DESDE TEXTO");

        jLabel7.setText("Cadena");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AFDTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AFNDTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 91, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AFDFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AFNDFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(141, 141, 141))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CadenaManualTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CadenaManualFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AFNDTexto)
                            .addComponent(AFDTexto))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(CadenaManualTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(CadenaManualFichero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AFDFichero)
                            .addComponent(AFNDFichero))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void AFDFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFDFicheroActionPerformed
        
        
        String cadena = CadenaManualFichero.getText();
           
        try {
           AutomataD a = Ficheros.LeerFicheroAFD(DIRECCION + "Test2AFD.txt");
           AFD afd = new AFD(a);       
                 SolucionAutomataD v = new SolucionAutomataD(a , cadena);               
                 v.setVisible(true);     
           System.out.println("Reconociendo cadena: "+ cadena +" ,para automata determinista , resultado: "+ (afd.reconocer(cadena)));
           
          
        } catch (IOException ex) {
            
        }
    }//GEN-LAST:event_AFDFicheroActionPerformed

    private void AFNDFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFNDFicheroActionPerformed
        
        String cadena = CadenaManualFichero.getText();
        
        try {
            AutomataND a = Ficheros.LeerFicheroAFND(DIRECCION + "Test2AFND.txt");
            AFND afnd = new AFND(a);
            
                   SolucionAutomataND v = new SolucionAutomataND(a,cadena);                
                    v.setVisible(true);  
                    
            System.out.println("Reconociendo cadena: "+  cadena +" ,para automata NO determinista , resultado: "+ (afnd.reconocer( cadena)));
        } catch (IOException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AFNDFicheroActionPerformed

    private void AFNDTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFNDTextoActionPerformed
       
        
        String cadena = CadenaManualTexto.getText();
        
        
        try {
           AutomataND  a = Ficheros.LeerTextoAFND(ZonaEscritura.getText());
            AFND afnd = new AFND(a);
                    SolucionAutomataND v = new SolucionAutomataND(a,cadena);
                         
                     v.setVisible(true); 
            System.out.println("Reconociendo cadena: "+  cadena +" ,para automata NO determinista , resultado: "+ (afnd.reconocer( cadena)));
        } catch (IOException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    }//GEN-LAST:event_AFNDTextoActionPerformed

    private void AFDTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFDTextoActionPerformed
        
                
        try {
            String cadena = CadenaManualTexto.getText();
            AutomataD a = Ficheros.LeerTextoAFD(ZonaEscritura.getText());
            AFD afd = new AFD(a);
            SolucionAutomataD v = new SolucionAutomataD(a,cadena);      
        
                      
                v.setVisible(true);  
                
            System.out.println("Reconociendo cadena: "+  cadena +" ,para automata determinista , resultado: "+ (afd.reconocer( cadena)));
            
        } catch (IOException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AFDTextoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        VentanaPrincipal vP = new VentanaPrincipal();
        vP.setVisible(true);
        vP.setTitle("Practica 2 AMC - Automatas - AJMM");
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AFDFichero;
    private javax.swing.JButton AFDTexto;
    private javax.swing.JButton AFNDFichero;
    private javax.swing.JButton AFNDTexto;
    private javax.swing.JTextField CadenaManualFichero;
    private javax.swing.JTextField CadenaManualTexto;
    private javax.swing.JTextArea ZonaEscritura;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
