/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Puntos.*;
import java.util.Random;

/**
 *
 * @author anton
 */
public class SolucionP1 extends java.awt.Frame {
     private static final String DIRECCION = "C:\\Users\\anton\\Desktop\\CURSO\\PracticasActuales\\AMC\\datos\\";
     
    /**
     * Creates new form SolucionP1
     */
    public SolucionP1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //PARTE EXHAUSTIVO FICHERO
        
      /* SolucionP1 v = new SolucionP1();
       CanvasParte1 cV = new CanvasParte1();
       
       v.setTitle("Solucion parte 1 - AMC - AJMM");
       v.setSize(1000, 1200);
       v.add(cV);
       v.setVisible(true);
       
       
       
        Punto[] puntos = TSPlib.leer(DIRECCION+"berlin52.tsp");
        Punto[] solucion = new Punto[3];            
        
         for(int i = 0 ; i < puntos.length ; i++)
         {
             System.out.println("Puntos: " + puntos[i].getX() + " " + puntos[i].getY());
         }
       try{
          
          Trio t = new Trio(Algoritmos.exhaustivo(puntos, 0, puntos.length-1));
          solucion[0] = t.getP0();
          solucion[1] = t.getP1();
          solucion[2] = t.getP2();
          
          System.out .println("Solucion exhaustivo: " + Algoritmos.exhaustivo(puntos,0,puntos.length-1));  
          
          
           
          cV.actualiza(puntos,solucion);
          
    }catch(Exception ex){
           System.out.println("ERROR EN LA SOLUCION");        
    }*/
      
      
      //PARTE EXHAUSTIVO RANDOM
      
      /* SolucionP1 v = new SolucionP1();
        CanvasParte1 cV = new CanvasParte1();
        
        Random r = new Random();
        r.setSeed(System.nanoTime());
        
        v.setTitle("Solucion parte 1 - EXHAUSTIVO - AMC - AJMM");
        v.setSize(1000, 1200);
        v.add(cV);
        v.setVisible(true);
        
        Punto[] solucion = new Punto[3]; 
        
        Punto[] puntos = new Punto[50];        
        for(int i = 0 ; i < 50 ; i++)
        {
            double x = (double) r.nextInt(701);
            double y = (double) r.nextInt(701);
            puntos[i]= new Punto(x,y);            
        }
        
        
        for(int i = 0 ; i < puntos.length ; i++)
         {
             System.out.println("Punto"+i+": " + puntos[i].getX() + " " + puntos[i].getY());
         }
        
        try{
          
          Trio t = new Trio(Algoritmos.exhaustivo(puntos, 0, puntos.length-1));
          solucion[0] = t.getP0();
          solucion[1] = t.getP1();
          solucion[2] = t.getP2();
          
          System.out .println("Solucion Exhaustivo: " + Algoritmos.exhaustivo(puntos,0,puntos.length-1));            
           
          cV.actualiza(puntos,solucion);
          
    }catch(Exception ex){
           System.out.println("ERROR EN LA SOLUCION");        
    }*/
      
      
      //PARTE DyV FICHERO
      
      
      
      //PARTE DyV RANDOM
      
      
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
