/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Algoritmos.Algoritmos;
import Caminos.*;
import Puntos.CanvasParte1;
import Puntos.Punto;
import Puntos.Ficheros;
import Puntos.Trio;
import java.awt.Canvas;
import java.util.Arrays;
import java.util.Random;

/**
 *
 * @author anton
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private static final String DIRECCION = "C:\\Users\\anton\\Desktop\\CURSO\\PracticasActuales\\AMC\\datos\\";
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonVorazFichero = new javax.swing.JButton();
        BotonDijkstra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TextoFicheroParte1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BotonVorazRandom = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextoFicheroDijkstra = new javax.swing.JTextField();
        BotonDyVFichero = new javax.swing.JButton();
        BotonDyVRandom = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TextoRandom = new javax.swing.JTextField();
        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Practica 1 AMC - AJMM");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        BotonVorazFichero.setText("Lanzar");
        BotonVorazFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVorazFicheroActionPerformed(evt);
            }
        });

        BotonDijkstra.setText("Lanzar");
        BotonDijkstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDijkstraActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Parte 1 - Voraz / DyV");

        jLabel2.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        jLabel2.setText("Fichero");

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setText("PRACTICA 1 - AMC");

        jLabel4.setText("Antonio Jose Morano Morina");

        BotonVorazRandom.setText("Lanzar");
        BotonVorazRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVorazRandomActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        jLabel5.setText("Puntos aleatorios");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Parte 2 - Dijkstra");

        jLabel7.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel7.setText("Fichero");

        BotonDyVFichero.setText("Lanzar");
        BotonDyVFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDyVFicheroActionPerformed(evt);
            }
        });

        BotonDyVRandom.setText("Lanzar");
        BotonDyVRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDyVRandomActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel8.setText("Voraz");

        jLabel9.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel9.setText("DyV");

        jLabel10.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel10.setText("DyV");

        jLabel11.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel11.setText("Voraz");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addGap(21, 21, 21))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(29, 29, 29))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotonVorazFichero)
                                    .addComponent(BotonDyVFichero)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BotonDyVRandom)
                                            .addComponent(BotonVorazRandom))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TextoRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextoFicheroParte1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(TextoFicheroDijkstra, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))
                        .addComponent(BotonDijkstra)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TextoFicheroParte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonVorazFichero)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonDyVFichero)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BotonVorazRandom))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BotonDyVRandom)
                                    .addComponent(jLabel9))
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(TextoRandom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BotonDijkstra)
                                    .addComponent(jLabel7)
                                    .addComponent(TextoFicheroDijkstra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonVorazFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVorazFicheroActionPerformed
        SolucionP1 v = new SolucionP1();
        CanvasParte1 cV = new CanvasParte1();
       
       v.setTitle("Solucion parte 1 - EXHAUSTIVO - AMC - AJMM");
       v.setSize(1000, 1200);
       v.add(cV);
       v.setVisible(true);
       
       
       
       // Punto[] puntos = Ficheros.leer(TextoFicheroParte1.getText());
        Punto[] puntos = Ficheros.leer(jFileChooser1.getName());
        Punto[] solucion = new Punto[3];  
        
        Algoritmos.QuickSort(puntos);
        
         for(int i = 0 ; i < puntos.length ; i++)
         {
             System.out.println("Punto"+i+": " + puntos[i].getX() + " " + puntos[i].getY());
         }
       try{
          
          Trio t = new Trio(Algoritmos.exhaustivo(puntos, 0, puntos.length-1));
          solucion[0] = t.getP0();
          solucion[1] = t.getP1();
          solucion[2] = t.getP2();
          
          System.out .println("Solucion exhaustivo: " + Algoritmos.exhaustivo(puntos,0,puntos.length-1));            
           
          cV.actualiza(puntos,solucion);
          
    }catch(Exception ex){
           System.out.println("ERROR EN LA SOLUCION");        
    }
    }//GEN-LAST:event_BotonVorazFicheroActionPerformed

    private void BotonVorazRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVorazRandomActionPerformed
        SolucionP1 v = new SolucionP1();
        CanvasParte1 cV = new CanvasParte1();
        
        Random r = new Random();
        r.setSeed(System.nanoTime());
        
        v.setTitle("Solucion parte 1 - AMC - AJMM");
        v.setSize(1000, 1200);
        v.add(cV);
        v.setVisible(true);
        
        int random = Integer.parseInt(TextoRandom.getText());
        
        Punto[] solucion = new Punto[3]; 
        
        Punto[] puntos = new Punto[random];        
        for(int i = 0 ; i < random ; i++)
        {
            double x = (double) r.nextInt(701);
            double y = (double) r.nextInt(701);
            puntos[i]= new Punto(x,y);
            
        }
        
        Algoritmos.QuickSort(puntos);
        
        for(int i = 0 ; i < puntos.length ; i++)
         {
             System.out.println("Punto"+i+": " + puntos[i].getX() + " " + puntos[i].getY());
         }
        
        try{
          
          Trio t = new Trio(Algoritmos.exhaustivo(puntos, 0, puntos.length-1));
          solucion[0] = t.getP0();
          solucion[1] = t.getP1();
          solucion[2] = t.getP2();
          
          System.out .println("Solucion Exhaustivo: " + Algoritmos.exhaustivo(puntos,0,puntos.length-1));            
           
          cV.actualiza(puntos,solucion);
          
    }catch(Exception ex){
           System.out.println("ERROR EN LA SOLUCION");        
    }
    }//GEN-LAST:event_BotonVorazRandomActionPerformed

    private void BotonDyVFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDyVFicheroActionPerformed
         SolucionP1 v = new SolucionP1();
         CanvasParte1 cV = new CanvasParte1();
       
         v.setTitle("Solucion parte 1  - AMC - AJMM");
         v.setSize(1000, 1200);
         v.add(cV);
         v.setVisible(true);
       
       
       
        Punto[] puntos = Ficheros.leer(TextoFicheroParte1.getText());
        Punto[] solucion = new Punto[3];
        
        Algoritmos.QuickSort(puntos);
        
         for(int i = 0 ; i < puntos.length ; i++)
         {
             System.out.println("Punto"+i+": " + puntos[i].getX() + " " + puntos[i].getY());
         }
       try{
          
          Trio t = new Trio(Algoritmos.exhaustivo(puntos, 0, puntos.length-1));
          solucion[0] = t.getP0();
          solucion[1] = t.getP1();
          solucion[2] = t.getP2();
          
          System.out .println("Solucion DyV: " + Algoritmos.DyV(puntos,0,puntos.length-1));            
           
          cV.actualiza(puntos,solucion);
          
    }catch(Exception ex){
           System.out.println("ERROR EN LA SOLUCION");        
    }
    }//GEN-LAST:event_BotonDyVFicheroActionPerformed

    private void BotonDyVRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDyVRandomActionPerformed
        SolucionP1 v = new SolucionP1();
        CanvasParte1 cV = new CanvasParte1();
        
        Random r = new Random();
        r.setSeed(System.nanoTime());
        
        v.setTitle("Solucion parte 1 - AMC - AJMM");
        v.setSize(1000, 1200);
        v.add(cV);
        v.setVisible(true);
        
        int random = Integer.parseInt(TextoRandom.getText());
        Punto[] solucion = new Punto[3]; 
        
        Punto[] puntos = new Punto[random];        
        for(int i = 0 ; i < random ; i++)
        {
            double x = (double) r.nextInt(701);
            double y = (double) r.nextInt(701);
            puntos[i]= new Punto(x,y);
            
        }
        
        Algoritmos.QuickSort(puntos);        
        
        for(int i = 0 ; i < puntos.length ; i++)
         {
             System.out.println("Punto"+i+": " + puntos[i].getX() + " " + puntos[i].getY());
         }
        
        try{
          
          Trio t = new Trio(Algoritmos.exhaustivo(puntos, 0, puntos.length-1));
          solucion[0] = t.getP0();
          solucion[1] = t.getP1();
          solucion[2] = t.getP2();
          
          System.out .println("Solucion DyV: " + Algoritmos.DyV(puntos,0,puntos.length-1));            
           
          cV.actualiza(puntos,solucion);
          
    }catch(Exception ex){
           System.out.println("ERROR EN LA SOLUCION");        
    }
    }//GEN-LAST:event_BotonDyVRandomActionPerformed

    private void BotonDijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDijkstraActionPerformed
        SolucionP2 v = new SolucionP2();
        CanvasParte2 cV = new CanvasParte2();
        
        Random r = new Random();
        r.setSeed(System.nanoTime());
        
        
        v.setTitle("Practica1 - AMC - AJMM - Dijkstra");
        v.setSize(1000, 1200);
        v.add(cV);
        v.setVisible(true);
        
         Punto[] puntos = Ficheros.leer(TextoFicheroDijkstra.getText());         
         Algoritmos.QuickSort(puntos);        
         double aux [][] = Algoritmos.mAdyacencia(puntos);
         int[] matriz = Algoritmos.Dijkstra(aux,0);
         int[] padres = Algoritmos.getPadres();                 
         
       try{
         //Ficheros.GuardarDijkstra(matriz, "b52", padres, 0);         
         System.out.println("Solucion Dijkstra : " + Arrays.toString(Algoritmos.Dijkstra(aux, 0)));
         
    }catch(Exception ex){
           System.out.println("ERROR EN LA SOLUCION");        
    }
       
        
        
    }//GEN-LAST:event_BotonDijkstraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        VentanaPrincipal vP = new VentanaPrincipal();
        vP.setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonDijkstra;
    private javax.swing.JButton BotonDyVFichero;
    private javax.swing.JButton BotonDyVRandom;
    private javax.swing.JButton BotonVorazFichero;
    private javax.swing.JButton BotonVorazRandom;
    private javax.swing.JTextField TextoFicheroDijkstra;
    private javax.swing.JTextField TextoFicheroParte1;
    private javax.swing.JTextField TextoRandom;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
